// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.2
// source: proto/gnpsi/gnpsi.proto

package gnpsi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SFlowMetadata_Version int32

const (
	SFlowMetadata_UNSPECIFIED SFlowMetadata_Version = 0
	SFlowMetadata_V2          SFlowMetadata_Version = 1
	SFlowMetadata_V5          SFlowMetadata_Version = 2
)

// Enum value maps for SFlowMetadata_Version.
var (
	SFlowMetadata_Version_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "V2",
		2: "V5",
	}
	SFlowMetadata_Version_value = map[string]int32{
		"UNSPECIFIED": 0,
		"V2":          1,
		"V5":          2,
	}
)

func (x SFlowMetadata_Version) Enum() *SFlowMetadata_Version {
	p := new(SFlowMetadata_Version)
	*p = x
	return p
}

func (x SFlowMetadata_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SFlowMetadata_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gnpsi_gnpsi_proto_enumTypes[0].Descriptor()
}

func (SFlowMetadata_Version) Type() protoreflect.EnumType {
	return &file_proto_gnpsi_gnpsi_proto_enumTypes[0]
}

func (x SFlowMetadata_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SFlowMetadata_Version.Descriptor instead.
func (SFlowMetadata_Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{0, 0}
}

type NetFlowMetadata_Version int32

const (
	NetFlowMetadata_UNSPECIFIED NetFlowMetadata_Version = 0
	NetFlowMetadata_V1          NetFlowMetadata_Version = 1
	NetFlowMetadata_V5          NetFlowMetadata_Version = 2
	NetFlowMetadata_V7          NetFlowMetadata_Version = 3
	NetFlowMetadata_V9          NetFlowMetadata_Version = 4
)

// Enum value maps for NetFlowMetadata_Version.
var (
	NetFlowMetadata_Version_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "V1",
		2: "V5",
		3: "V7",
		4: "V9",
	}
	NetFlowMetadata_Version_value = map[string]int32{
		"UNSPECIFIED": 0,
		"V1":          1,
		"V5":          2,
		"V7":          3,
		"V9":          4,
	}
)

func (x NetFlowMetadata_Version) Enum() *NetFlowMetadata_Version {
	p := new(NetFlowMetadata_Version)
	*p = x
	return p
}

func (x NetFlowMetadata_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetFlowMetadata_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gnpsi_gnpsi_proto_enumTypes[1].Descriptor()
}

func (NetFlowMetadata_Version) Type() protoreflect.EnumType {
	return &file_proto_gnpsi_gnpsi_proto_enumTypes[1]
}

func (x NetFlowMetadata_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetFlowMetadata_Version.Descriptor instead.
func (NetFlowMetadata_Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{1, 0}
}

type IPFIXMetadata_Version int32

const (
	IPFIXMetadata_UNSPECIFIED IPFIXMetadata_Version = 0
	IPFIXMetadata_V10         IPFIXMetadata_Version = 1
)

// Enum value maps for IPFIXMetadata_Version.
var (
	IPFIXMetadata_Version_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "V10",
	}
	IPFIXMetadata_Version_value = map[string]int32{
		"UNSPECIFIED": 0,
		"V10":         1,
	}
)

func (x IPFIXMetadata_Version) Enum() *IPFIXMetadata_Version {
	p := new(IPFIXMetadata_Version)
	*p = x
	return p
}

func (x IPFIXMetadata_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPFIXMetadata_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gnpsi_gnpsi_proto_enumTypes[2].Descriptor()
}

func (IPFIXMetadata_Version) Type() protoreflect.EnumType {
	return &file_proto_gnpsi_gnpsi_proto_enumTypes[2]
}

func (x IPFIXMetadata_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPFIXMetadata_Version.Descriptor instead.
func (IPFIXMetadata_Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{2, 0}
}

type SFlowMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version SFlowMetadata_Version `protobuf:"varint,1,opt,name=version,proto3,enum=gnpsi.SFlowMetadata_Version" json:"version,omitempty"`
}

func (x *SFlowMetadata) Reset() {
	*x = SFlowMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFlowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFlowMetadata) ProtoMessage() {}

func (x *SFlowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFlowMetadata.ProtoReflect.Descriptor instead.
func (*SFlowMetadata) Descriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{0}
}

func (x *SFlowMetadata) GetVersion() SFlowMetadata_Version {
	if x != nil {
		return x.Version
	}
	return SFlowMetadata_UNSPECIFIED
}

type NetFlowMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version NetFlowMetadata_Version `protobuf:"varint,1,opt,name=version,proto3,enum=gnpsi.NetFlowMetadata_Version" json:"version,omitempty"`
}

func (x *NetFlowMetadata) Reset() {
	*x = NetFlowMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetFlowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetFlowMetadata) ProtoMessage() {}

func (x *NetFlowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetFlowMetadata.ProtoReflect.Descriptor instead.
func (*NetFlowMetadata) Descriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{1}
}

func (x *NetFlowMetadata) GetVersion() NetFlowMetadata_Version {
	if x != nil {
		return x.Version
	}
	return NetFlowMetadata_UNSPECIFIED
}

type IPFIXMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version IPFIXMetadata_Version `protobuf:"varint,1,opt,name=version,proto3,enum=gnpsi.IPFIXMetadata_Version" json:"version,omitempty"`
}

func (x *IPFIXMetadata) Reset() {
	*x = IPFIXMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPFIXMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPFIXMetadata) ProtoMessage() {}

func (x *IPFIXMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPFIXMetadata.ProtoReflect.Descriptor instead.
func (*IPFIXMetadata) Descriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{2}
}

func (x *IPFIXMetadata) GetVersion() IPFIXMetadata_Version {
	if x != nil {
		return x.Version
	}
	return IPFIXMetadata_UNSPECIFIED
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{3}
}

type Sample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packet          []byte           `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Timestamp       int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SflowMetadata   *SFlowMetadata   `protobuf:"bytes,101,opt,name=sflow_metadata,json=sflowMetadata,proto3" json:"sflow_metadata,omitempty"`
	NetflowMetadata *NetFlowMetadata `protobuf:"bytes,102,opt,name=netflow_metadata,json=netflowMetadata,proto3" json:"netflow_metadata,omitempty"`
	IpfixMetadata   *IPFIXMetadata   `protobuf:"bytes,103,opt,name=ipfix_metadata,json=ipfixMetadata,proto3" json:"ipfix_metadata,omitempty"`
}

func (x *Sample) Reset() {
	*x = Sample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gnpsi_gnpsi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_gnpsi_gnpsi_proto_rawDescGZIP(), []int{4}
}

func (x *Sample) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *Sample) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Sample) GetSflowMetadata() *SFlowMetadata {
	if x != nil {
		return x.SflowMetadata
	}
	return nil
}

func (x *Sample) GetNetflowMetadata() *NetFlowMetadata {
	if x != nil {
		return x.NetflowMetadata
	}
	return nil
}

func (x *Sample) GetIpfixMetadata() *IPFIXMetadata {
	if x != nil {
		return x.IpfixMetadata
	}
	return nil
}

var File_proto_gnpsi_gnpsi_proto protoreflect.FileDescriptor

var file_proto_gnpsi_gnpsi_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2f, 0x67, 0x6e,
	0x70, 0x73, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6e, 0x70, 0x73, 0x69,
	0x22, 0x73, 0x0a, 0x0d, 0x53, 0x46, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x36, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2e, 0x53, 0x46, 0x6c, 0x6f, 0x77,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x32, 0x10, 0x01, 0x12, 0x06, 0x0a,
	0x02, 0x56, 0x35, 0x10, 0x02, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x46, 0x6c, 0x6f,
	0x77, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x6e, 0x70,
	0x73, 0x69, 0x2e, 0x4e, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x31, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x35, 0x10, 0x02, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x37, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x39, 0x10, 0x04, 0x22,
	0x6c, 0x0a, 0x0d, 0x49, 0x50, 0x46, 0x49, 0x58, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x36, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2e, 0x49, 0x50, 0x46, 0x49, 0x58, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x31, 0x30, 0x10, 0x01, 0x22, 0x09, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xfb, 0x01, 0x0a, 0x06, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3b, 0x0a, 0x0e, 0x73, 0x66, 0x6c,
	0x6f, 0x77, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x65, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2e, 0x53, 0x46, 0x6c, 0x6f, 0x77, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x73, 0x66, 0x6c, 0x6f, 0x77, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x10, 0x6e, 0x65, 0x74, 0x66, 0x6c, 0x6f,
	0x77, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2e, 0x4e, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x6e, 0x65, 0x74, 0x66, 0x6c, 0x6f,
	0x77, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0e, 0x69, 0x70, 0x66,
	0x69, 0x78, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2e, 0x49, 0x50, 0x46, 0x49, 0x58, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x69, 0x70, 0x66, 0x69, 0x78, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x32, 0x35, 0x0a, 0x05, 0x67, 0x4e, 0x50, 0x53, 0x49, 0x12,
	0x2c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x0e, 0x2e, 0x67,
	0x6e, 0x70, 0x73, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x67,
	0x6e, 0x70, 0x73, 0x69, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x30, 0x01, 0x42, 0x29, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6e, 0x70, 0x73, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gnpsi_gnpsi_proto_rawDescOnce sync.Once
	file_proto_gnpsi_gnpsi_proto_rawDescData = file_proto_gnpsi_gnpsi_proto_rawDesc
)

func file_proto_gnpsi_gnpsi_proto_rawDescGZIP() []byte {
	file_proto_gnpsi_gnpsi_proto_rawDescOnce.Do(func() {
		file_proto_gnpsi_gnpsi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gnpsi_gnpsi_proto_rawDescData)
	})
	return file_proto_gnpsi_gnpsi_proto_rawDescData
}

var file_proto_gnpsi_gnpsi_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_gnpsi_gnpsi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gnpsi_gnpsi_proto_goTypes = []interface{}{
	(SFlowMetadata_Version)(0),   // 0: gnpsi.SFlowMetadata.Version
	(NetFlowMetadata_Version)(0), // 1: gnpsi.NetFlowMetadata.Version
	(IPFIXMetadata_Version)(0),   // 2: gnpsi.IPFIXMetadata.Version
	(*SFlowMetadata)(nil),        // 3: gnpsi.SFlowMetadata
	(*NetFlowMetadata)(nil),      // 4: gnpsi.NetFlowMetadata
	(*IPFIXMetadata)(nil),        // 5: gnpsi.IPFIXMetadata
	(*Request)(nil),              // 6: gnpsi.Request
	(*Sample)(nil),               // 7: gnpsi.Sample
}
var file_proto_gnpsi_gnpsi_proto_depIdxs = []int32{
	0, // 0: gnpsi.SFlowMetadata.version:type_name -> gnpsi.SFlowMetadata.Version
	1, // 1: gnpsi.NetFlowMetadata.version:type_name -> gnpsi.NetFlowMetadata.Version
	2, // 2: gnpsi.IPFIXMetadata.version:type_name -> gnpsi.IPFIXMetadata.Version
	3, // 3: gnpsi.Sample.sflow_metadata:type_name -> gnpsi.SFlowMetadata
	4, // 4: gnpsi.Sample.netflow_metadata:type_name -> gnpsi.NetFlowMetadata
	5, // 5: gnpsi.Sample.ipfix_metadata:type_name -> gnpsi.IPFIXMetadata
	6, // 6: gnpsi.gNPSI.Subscribe:input_type -> gnpsi.Request
	7, // 7: gnpsi.gNPSI.Subscribe:output_type -> gnpsi.Sample
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_gnpsi_gnpsi_proto_init() }
func file_proto_gnpsi_gnpsi_proto_init() {
	if File_proto_gnpsi_gnpsi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gnpsi_gnpsi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFlowMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnpsi_gnpsi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetFlowMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnpsi_gnpsi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPFIXMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnpsi_gnpsi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gnpsi_gnpsi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gnpsi_gnpsi_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gnpsi_gnpsi_proto_goTypes,
		DependencyIndexes: file_proto_gnpsi_gnpsi_proto_depIdxs,
		EnumInfos:         file_proto_gnpsi_gnpsi_proto_enumTypes,
		MessageInfos:      file_proto_gnpsi_gnpsi_proto_msgTypes,
	}.Build()
	File_proto_gnpsi_gnpsi_proto = out.File
	file_proto_gnpsi_gnpsi_proto_rawDesc = nil
	file_proto_gnpsi_gnpsi_proto_goTypes = nil
	file_proto_gnpsi_gnpsi_proto_depIdxs = nil
}
