// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gnpsi.proto

#include "gnpsi.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gnpsi {

inline constexpr SFlowMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_{static_cast< ::gnpsi::SFlowMetadata_Version >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SFlowMetadata::SFlowMetadata(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SFlowMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SFlowMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SFlowMetadataDefaultTypeInternal() {}
  union {
    SFlowMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SFlowMetadataDefaultTypeInternal _SFlowMetadata_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Request::Request(::_pbi::ConstantInitialized) {}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;

inline constexpr NetFlowMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_{static_cast< ::gnpsi::NetFlowMetadata_Version >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NetFlowMetadata::NetFlowMetadata(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NetFlowMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NetFlowMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NetFlowMetadataDefaultTypeInternal() {}
  union {
    NetFlowMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NetFlowMetadataDefaultTypeInternal _NetFlowMetadata_default_instance_;

inline constexpr IPFIXMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_{static_cast< ::gnpsi::IPFIXMetadata_Version >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR IPFIXMetadata::IPFIXMetadata(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct IPFIXMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IPFIXMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IPFIXMetadataDefaultTypeInternal() {}
  union {
    IPFIXMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IPFIXMetadataDefaultTypeInternal _IPFIXMetadata_default_instance_;

inline constexpr Sample::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        packet_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sflow_metadata_{nullptr},
        netflow_metadata_{nullptr},
        ipfix_metadata_{nullptr},
        timestamp_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Sample::Sample(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SampleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SampleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SampleDefaultTypeInternal() {}
  union {
    Sample _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SampleDefaultTypeInternal _Sample_default_instance_;
}  // namespace gnpsi
static ::_pb::Metadata file_level_metadata_gnpsi_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_gnpsi_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gnpsi_2eproto = nullptr;
const ::uint32_t
    TableStruct_gnpsi_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gnpsi::SFlowMetadata, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gnpsi::SFlowMetadata, _impl_.version_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gnpsi::NetFlowMetadata, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gnpsi::NetFlowMetadata, _impl_.version_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gnpsi::IPFIXMetadata, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gnpsi::IPFIXMetadata, _impl_.version_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gnpsi::Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_.packet_),
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_.sflow_metadata_),
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_.netflow_metadata_),
        PROTOBUF_FIELD_OFFSET(::gnpsi::Sample, _impl_.ipfix_metadata_),
        ~0u,
        ~0u,
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::gnpsi::SFlowMetadata)},
        {9, -1, -1, sizeof(::gnpsi::NetFlowMetadata)},
        {18, -1, -1, sizeof(::gnpsi::IPFIXMetadata)},
        {27, -1, -1, sizeof(::gnpsi::Request)},
        {35, 48, -1, sizeof(::gnpsi::Sample)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::gnpsi::_SFlowMetadata_default_instance_._instance,
    &::gnpsi::_NetFlowMetadata_default_instance_._instance,
    &::gnpsi::_IPFIXMetadata_default_instance_._instance,
    &::gnpsi::_Request_default_instance_._instance,
    &::gnpsi::_Sample_default_instance_._instance,
};
const char descriptor_table_protodef_gnpsi_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013gnpsi.proto\022\005gnpsi\"j\n\rSFlowMetadata\022-\n"
    "\007version\030\001 \001(\0162\034.gnpsi.SFlowMetadata.Ver"
    "sion\"*\n\007Version\022\017\n\013UNSPECIFIED\020\000\022\006\n\002V2\020\001"
    "\022\006\n\002V5\020\002\"~\n\017NetFlowMetadata\022/\n\007version\030\001"
    " \001(\0162\036.gnpsi.NetFlowMetadata.Version\":\n\007"
    "Version\022\017\n\013UNSPECIFIED\020\000\022\006\n\002V1\020\001\022\006\n\002V5\020\002"
    "\022\006\n\002V7\020\003\022\006\n\002V9\020\004\"c\n\rIPFIXMetadata\022-\n\007ver"
    "sion\030\001 \001(\0162\034.gnpsi.IPFIXMetadata.Version"
    "\"#\n\007Version\022\017\n\013UNSPECIFIED\020\000\022\007\n\003V10\020\001\"\t\n"
    "\007Request\"\271\001\n\006Sample\022\016\n\006packet\030\001 \001(\014\022\021\n\tt"
    "imestamp\030\002 \001(\003\022,\n\016sflow_metadata\030e \001(\0132\024"
    ".gnpsi.SFlowMetadata\0220\n\020netflow_metadata"
    "\030f \001(\0132\026.gnpsi.NetFlowMetadata\022,\n\016ipfix_"
    "metadata\030g \001(\0132\024.gnpsi.IPFIXMetadata25\n\005"
    "gNPSI\022,\n\tSubscribe\022\016.gnpsi.Request\032\r.gnp"
    "si.Sample0\001B)Z\'github.com/openconfig/gnp"
    "si/proto/gnpsib\006proto3"
};
static ::absl::once_flag descriptor_table_gnpsi_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_gnpsi_2eproto = {
    false,
    false,
    662,
    descriptor_table_protodef_gnpsi_2eproto,
    "gnpsi.proto",
    &descriptor_table_gnpsi_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_gnpsi_2eproto::offsets,
    file_level_metadata_gnpsi_2eproto,
    file_level_enum_descriptors_gnpsi_2eproto,
    file_level_service_descriptors_gnpsi_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_gnpsi_2eproto_getter() {
  return &descriptor_table_gnpsi_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_gnpsi_2eproto(&descriptor_table_gnpsi_2eproto);
namespace gnpsi {
const ::google::protobuf::EnumDescriptor* SFlowMetadata_Version_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_gnpsi_2eproto);
  return file_level_enum_descriptors_gnpsi_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SFlowMetadata_Version_internal_data_[] = {
    196608u, 0u, };
bool SFlowMetadata_Version_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr SFlowMetadata_Version SFlowMetadata::UNSPECIFIED;
constexpr SFlowMetadata_Version SFlowMetadata::V2;
constexpr SFlowMetadata_Version SFlowMetadata::V5;
constexpr SFlowMetadata_Version SFlowMetadata::Version_MIN;
constexpr SFlowMetadata_Version SFlowMetadata::Version_MAX;
constexpr int SFlowMetadata::Version_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* NetFlowMetadata_Version_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_gnpsi_2eproto);
  return file_level_enum_descriptors_gnpsi_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t NetFlowMetadata_Version_internal_data_[] = {
    327680u, 0u, };
bool NetFlowMetadata_Version_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr NetFlowMetadata_Version NetFlowMetadata::UNSPECIFIED;
constexpr NetFlowMetadata_Version NetFlowMetadata::V1;
constexpr NetFlowMetadata_Version NetFlowMetadata::V5;
constexpr NetFlowMetadata_Version NetFlowMetadata::V7;
constexpr NetFlowMetadata_Version NetFlowMetadata::V9;
constexpr NetFlowMetadata_Version NetFlowMetadata::Version_MIN;
constexpr NetFlowMetadata_Version NetFlowMetadata::Version_MAX;
constexpr int NetFlowMetadata::Version_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* IPFIXMetadata_Version_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_gnpsi_2eproto);
  return file_level_enum_descriptors_gnpsi_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t IPFIXMetadata_Version_internal_data_[] = {
    131072u, 0u, };
bool IPFIXMetadata_Version_IsValid(int value) {
  return 0 <= value && value <= 1;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr IPFIXMetadata_Version IPFIXMetadata::UNSPECIFIED;
constexpr IPFIXMetadata_Version IPFIXMetadata::V10;
constexpr IPFIXMetadata_Version IPFIXMetadata::Version_MIN;
constexpr IPFIXMetadata_Version IPFIXMetadata::Version_MAX;
constexpr int IPFIXMetadata::Version_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class SFlowMetadata::_Internal {
 public:
};

SFlowMetadata::SFlowMetadata(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gnpsi.SFlowMetadata)
}
SFlowMetadata::SFlowMetadata(
    ::google::protobuf::Arena* arena, const SFlowMetadata& from)
    : SFlowMetadata(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SFlowMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SFlowMetadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
SFlowMetadata::~SFlowMetadata() {
  // @@protoc_insertion_point(destructor:gnpsi.SFlowMetadata)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SFlowMetadata::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SFlowMetadata::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          SFlowMetadata::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void SFlowMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:gnpsi.SFlowMetadata)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SFlowMetadata::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SFlowMetadata::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SFlowMetadata_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .gnpsi.SFlowMetadata.Version version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SFlowMetadata, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SFlowMetadata, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .gnpsi.SFlowMetadata.Version version = 1;
    {PROTOBUF_FIELD_OFFSET(SFlowMetadata, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* SFlowMetadata::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gnpsi.SFlowMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .gnpsi.SFlowMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gnpsi.SFlowMetadata)
  return target;
}

::size_t SFlowMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gnpsi.SFlowMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .gnpsi.SFlowMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SFlowMetadata::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SFlowMetadata*>(&to_msg);
  auto& from = static_cast<const SFlowMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gnpsi.SFlowMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SFlowMetadata::CopyFrom(const SFlowMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gnpsi.SFlowMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SFlowMetadata::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SFlowMetadata::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SFlowMetadata::InternalSwap(SFlowMetadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata SFlowMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gnpsi_2eproto_getter, &descriptor_table_gnpsi_2eproto_once,
      file_level_metadata_gnpsi_2eproto[0]);
}
// ===================================================================

class NetFlowMetadata::_Internal {
 public:
};

NetFlowMetadata::NetFlowMetadata(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gnpsi.NetFlowMetadata)
}
NetFlowMetadata::NetFlowMetadata(
    ::google::protobuf::Arena* arena, const NetFlowMetadata& from)
    : NetFlowMetadata(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE NetFlowMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void NetFlowMetadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
NetFlowMetadata::~NetFlowMetadata() {
  // @@protoc_insertion_point(destructor:gnpsi.NetFlowMetadata)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NetFlowMetadata::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
NetFlowMetadata::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          NetFlowMetadata::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void NetFlowMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:gnpsi.NetFlowMetadata)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NetFlowMetadata::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> NetFlowMetadata::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NetFlowMetadata_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .gnpsi.NetFlowMetadata.Version version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NetFlowMetadata, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NetFlowMetadata, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .gnpsi.NetFlowMetadata.Version version = 1;
    {PROTOBUF_FIELD_OFFSET(NetFlowMetadata, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* NetFlowMetadata::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gnpsi.NetFlowMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .gnpsi.NetFlowMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gnpsi.NetFlowMetadata)
  return target;
}

::size_t NetFlowMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gnpsi.NetFlowMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .gnpsi.NetFlowMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void NetFlowMetadata::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<NetFlowMetadata*>(&to_msg);
  auto& from = static_cast<const NetFlowMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gnpsi.NetFlowMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NetFlowMetadata::CopyFrom(const NetFlowMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gnpsi.NetFlowMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NetFlowMetadata::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* NetFlowMetadata::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void NetFlowMetadata::InternalSwap(NetFlowMetadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata NetFlowMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gnpsi_2eproto_getter, &descriptor_table_gnpsi_2eproto_once,
      file_level_metadata_gnpsi_2eproto[1]);
}
// ===================================================================

class IPFIXMetadata::_Internal {
 public:
};

IPFIXMetadata::IPFIXMetadata(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gnpsi.IPFIXMetadata)
}
IPFIXMetadata::IPFIXMetadata(
    ::google::protobuf::Arena* arena, const IPFIXMetadata& from)
    : IPFIXMetadata(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE IPFIXMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void IPFIXMetadata::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
IPFIXMetadata::~IPFIXMetadata() {
  // @@protoc_insertion_point(destructor:gnpsi.IPFIXMetadata)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void IPFIXMetadata::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
IPFIXMetadata::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          IPFIXMetadata::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void IPFIXMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:gnpsi.IPFIXMetadata)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* IPFIXMetadata::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> IPFIXMetadata::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_IPFIXMetadata_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .gnpsi.IPFIXMetadata.Version version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IPFIXMetadata, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(IPFIXMetadata, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .gnpsi.IPFIXMetadata.Version version = 1;
    {PROTOBUF_FIELD_OFFSET(IPFIXMetadata, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* IPFIXMetadata::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gnpsi.IPFIXMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .gnpsi.IPFIXMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gnpsi.IPFIXMetadata)
  return target;
}

::size_t IPFIXMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gnpsi.IPFIXMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .gnpsi.IPFIXMetadata.Version version = 1;
  if (this->_internal_version() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void IPFIXMetadata::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<IPFIXMetadata*>(&to_msg);
  auto& from = static_cast<const IPFIXMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gnpsi.IPFIXMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void IPFIXMetadata::CopyFrom(const IPFIXMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gnpsi.IPFIXMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool IPFIXMetadata::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* IPFIXMetadata::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void IPFIXMetadata::InternalSwap(IPFIXMetadata* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata IPFIXMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gnpsi_2eproto_getter, &descriptor_table_gnpsi_2eproto_once,
      file_level_metadata_gnpsi_2eproto[2]);
}
// ===================================================================

class Request::_Internal {
 public:
};

Request::Request(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:gnpsi.Request)
}
Request::Request(
    ::google::protobuf::Arena* arena,
    const Request& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:gnpsi.Request)
}









::google::protobuf::Metadata Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gnpsi_2eproto_getter, &descriptor_table_gnpsi_2eproto_once,
      file_level_metadata_gnpsi_2eproto[3]);
}
// ===================================================================

class Sample::_Internal {
 public:
  using HasBits = decltype(std::declval<Sample>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Sample, _impl_._has_bits_);
  static const ::gnpsi::SFlowMetadata& sflow_metadata(const Sample* msg);
  static void set_has_sflow_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::gnpsi::NetFlowMetadata& netflow_metadata(const Sample* msg);
  static void set_has_netflow_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::gnpsi::IPFIXMetadata& ipfix_metadata(const Sample* msg);
  static void set_has_ipfix_metadata(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::gnpsi::SFlowMetadata& Sample::_Internal::sflow_metadata(const Sample* msg) {
  return *msg->_impl_.sflow_metadata_;
}
const ::gnpsi::NetFlowMetadata& Sample::_Internal::netflow_metadata(const Sample* msg) {
  return *msg->_impl_.netflow_metadata_;
}
const ::gnpsi::IPFIXMetadata& Sample::_Internal::ipfix_metadata(const Sample* msg) {
  return *msg->_impl_.ipfix_metadata_;
}
Sample::Sample(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gnpsi.Sample)
}
inline PROTOBUF_NDEBUG_INLINE Sample::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        packet_(arena, from.packet_) {}

Sample::Sample(
    ::google::protobuf::Arena* arena,
    const Sample& from)
    : ::google::protobuf::Message(arena) {
  Sample* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.sflow_metadata_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::gnpsi::SFlowMetadata>(arena, *from._impl_.sflow_metadata_)
                : nullptr;
  _impl_.netflow_metadata_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::gnpsi::NetFlowMetadata>(arena, *from._impl_.netflow_metadata_)
                : nullptr;
  _impl_.ipfix_metadata_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::gnpsi::IPFIXMetadata>(arena, *from._impl_.ipfix_metadata_)
                : nullptr;
  _impl_.timestamp_ = from._impl_.timestamp_;

  // @@protoc_insertion_point(copy_constructor:gnpsi.Sample)
}
inline PROTOBUF_NDEBUG_INLINE Sample::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        packet_(arena) {}

inline void Sample::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sflow_metadata_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, sflow_metadata_) +
               sizeof(Impl_::timestamp_));
}
Sample::~Sample() {
  // @@protoc_insertion_point(destructor:gnpsi.Sample)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Sample::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.packet_.Destroy();
  delete _impl_.sflow_metadata_;
  delete _impl_.netflow_metadata_;
  delete _impl_.ipfix_metadata_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Sample::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          Sample::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void Sample::Clear() {
// @@protoc_insertion_point(message_clear_start:gnpsi.Sample)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.packet_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.sflow_metadata_ != nullptr);
      _impl_.sflow_metadata_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.netflow_metadata_ != nullptr);
      _impl_.netflow_metadata_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.ipfix_metadata_ != nullptr);
      _impl_.ipfix_metadata_->Clear();
    }
  }
  _impl_.timestamp_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Sample::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 3, 0, 7> Sample::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Sample, _impl_._has_bits_),
    0, // no _extensions_
    103, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Sample_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes packet = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Sample, _impl_.packet_)}},
    // int64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Sample, _impl_.timestamp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Sample, _impl_.timestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // .gnpsi.SFlowMetadata sflow_metadata = 101;
    {::_pbi::TcParser::FastMtS2,
     {1706, 0, 0, PROTOBUF_FIELD_OFFSET(Sample, _impl_.sflow_metadata_)}},
    // .gnpsi.NetFlowMetadata netflow_metadata = 102;
    {::_pbi::TcParser::FastMtS2,
     {1714, 1, 1, PROTOBUF_FIELD_OFFSET(Sample, _impl_.netflow_metadata_)}},
    // .gnpsi.IPFIXMetadata ipfix_metadata = 103;
    {::_pbi::TcParser::FastMtS2,
     {1722, 2, 2, PROTOBUF_FIELD_OFFSET(Sample, _impl_.ipfix_metadata_)}},
  }}, {{
    101, 0, 1,
    65528, 2,
    65535, 65535
  }}, {{
    // bytes packet = 1;
    {PROTOBUF_FIELD_OFFSET(Sample, _impl_.packet_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(Sample, _impl_.timestamp_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .gnpsi.SFlowMetadata sflow_metadata = 101;
    {PROTOBUF_FIELD_OFFSET(Sample, _impl_.sflow_metadata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .gnpsi.NetFlowMetadata netflow_metadata = 102;
    {PROTOBUF_FIELD_OFFSET(Sample, _impl_.netflow_metadata_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .gnpsi.IPFIXMetadata ipfix_metadata = 103;
    {PROTOBUF_FIELD_OFFSET(Sample, _impl_.ipfix_metadata_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::gnpsi::SFlowMetadata>()},
    {::_pbi::TcParser::GetTable<::gnpsi::NetFlowMetadata>()},
    {::_pbi::TcParser::GetTable<::gnpsi::IPFIXMetadata>()},
  }}, {{
  }},
};

::uint8_t* Sample::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gnpsi.Sample)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes packet = 1;
  if (!this->_internal_packet().empty()) {
    const std::string& _s = this->_internal_packet();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_timestamp(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .gnpsi.SFlowMetadata sflow_metadata = 101;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        101, _Internal::sflow_metadata(this),
        _Internal::sflow_metadata(this).GetCachedSize(), target, stream);
  }

  // .gnpsi.NetFlowMetadata netflow_metadata = 102;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        102, _Internal::netflow_metadata(this),
        _Internal::netflow_metadata(this).GetCachedSize(), target, stream);
  }

  // .gnpsi.IPFIXMetadata ipfix_metadata = 103;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        103, _Internal::ipfix_metadata(this),
        _Internal::ipfix_metadata(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gnpsi.Sample)
  return target;
}

::size_t Sample::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gnpsi.Sample)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes packet = 1;
  if (!this->_internal_packet().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_packet());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // .gnpsi.SFlowMetadata sflow_metadata = 101;
    if (cached_has_bits & 0x00000001u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.sflow_metadata_);
    }

    // .gnpsi.NetFlowMetadata netflow_metadata = 102;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.netflow_metadata_);
    }

    // .gnpsi.IPFIXMetadata ipfix_metadata = 103;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.ipfix_metadata_);
    }

  }
  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Sample::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Sample*>(&to_msg);
  auto& from = static_cast<const Sample&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gnpsi.Sample)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_packet().empty()) {
    _this->_internal_set_packet(from._internal_packet());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_sflow_metadata()->::gnpsi::SFlowMetadata::MergeFrom(
          from._internal_sflow_metadata());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_netflow_metadata()->::gnpsi::NetFlowMetadata::MergeFrom(
          from._internal_netflow_metadata());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_ipfix_metadata()->::gnpsi::IPFIXMetadata::MergeFrom(
          from._internal_ipfix_metadata());
    }
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Sample::CopyFrom(const Sample& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gnpsi.Sample)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Sample::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Sample::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Sample::InternalSwap(Sample* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.packet_, &other->_impl_.packet_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sample, _impl_.timestamp_)
      + sizeof(Sample::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(Sample, _impl_.sflow_metadata_)>(
          reinterpret_cast<char*>(&_impl_.sflow_metadata_),
          reinterpret_cast<char*>(&other->_impl_.sflow_metadata_));
}

::google::protobuf::Metadata Sample::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_gnpsi_2eproto_getter, &descriptor_table_gnpsi_2eproto_once,
      file_level_metadata_gnpsi_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gnpsi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
